version: "3"

services:
  web:
    platform: linux/amd64 # Just to do compatible with arm64 mac m1 for example 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql2://the_user:the_password@db:3306/development"

  db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: development
      MYSQL_USER: the_user
      MYSQL_PASSWORD: the_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
