version: "3"

services:
  web:
    platform: linux/amd64 # Just to do compatible with arm64 mac m1 for example 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql2://the_user:the_password@db:3306/development"

  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: development
      MYSQL_USER: the_user
      MYSQL_PASSWORD: the_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    platform: linux/amd64
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  sidekiq:
    platform: linux/amd64
    depends_on:
      - 'db'
      - 'redis'
      - 'web'
    build: .
    volumes:
      - ".:/usr/src/app"
    command: bundle exec sidekiq # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  mysql_data:
  redis:
